version: '3.9'
services:
  db:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: councilworks
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/db:/docker-entrypoint-initdb.d
  app:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/councilworks
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run dev"
volumes:
  db_data:
