version: '3.9'
services:
  db:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: councilworks
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d councilworks -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 15
  app:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/councilworks
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "until pg_isready -h db -p 5432 -U postgres; do echo waiting for db; sleep 1; done; npx prisma migrate deploy && npm run dev"
volumes:
  db_data:
