name: User Story
description: Create a user story for implementation
labels: ["story"]
title: "US: "
body:
  - type: textarea
    id: story
    attributes:
      label: User Story
      description: As a [user], I want [function], so that [value].
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Bullet list of testable criteria
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: input
    id: points
    attributes:
      label: Story Points (Fibonacci)
      placeholder: 1,2,3,5,8,13,21
