name: Container Security Scan

on:
  push:
    branches: [main, develop]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.dockerignore'
  pull_request:
    branches: [main, develop]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.dockerignore'
  schedule:
    # Run container security scans weekly
    - cron: '0 3 * * 1'

jobs:
  container-security:
    name: Container Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t councilworks:${{ github.sha }} .
          docker tag councilworks:${{ github.sha }} councilworks:latest

      - name: Run Snyk Container Scan
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: councilworks:${{ github.sha }}
          args: --severity-threshold=medium --file=Dockerfile

      - name: Run Trivy Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'councilworks:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Security Summary
        run: |
          echo "## Container Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Docker image built successfully" >> $GITHUB_STEP_SUMMARY
          echo "✅ Snyk container scan completed" >> $GITHUB_STEP_SUMMARY
          echo "✅ Trivy container scan completed" >> $GITHUB_STEP_SUMMARY
          echo "📊 Results uploaded to GitHub Security tab" >> $GITHUB_STEP_SUMMARY
